In [1]:
import pandas as pd
import pickle
import xlrd

In [2]:
%%time

HCPCS_rows =[]
for chunk in pd.read_csv('../data/Medicare_Provider_Utilization_and_Payment_Data__Physician_and_Other_Supplier_PUF_CY2017.csv', 
                         dtype = {'Zip Code of the Provider': str},
                         chunksize = 1000):
    HCPCS_rows.append(chunk[chunk['HCPCS Code'] == '43249']) 
               
                
hcpcs_pay_43249 = pd.concat(HCPCS_rows, ignore_index=True)

Wall time: 2min 4s

In [3]:
print(hcpcs_pay_43249.shape)
print(hcpcs_pay_43249.info())
hcpcs_pay_43249.head()

(3161, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3161 entries, 0 to 3160
Data columns (total 26 columns):
National Provider Identifier                                3161 non-null int64
Last Name/Organization Name of the Provider                 3161 non-null object
First Name of the Provider                                  2544 non-null object
Middle Initial of the Provider                              1918 non-null object
Credentials of the Provider                                 2504 non-null object
Gender of the Provider                                      2544 non-null object
Entity Type of the Provider                                 3161 non-null object
Street Address 1 of the Provider                            3161 non-null object
Street Address 2 of the Provider                            1675 non-null object
City of the Provider                                        3161 non-null object
Zip Code of the Provider                                    3161 non-null object
State Code of the Provider                                  3161 non-null object
Country Code of the Provider                                3161 non-null object
Provider Type                                               3161 non-null object
Medicare Participation Indicator                            3161 non-null object
Place of Service                                            3161 non-null object
HCPCS Code                                                  3161 non-null object
HCPCS Description                                           3161 non-null object
HCPCS Drug Indicator                                        3161 non-null object
Number of Services                                          3161 non-null float64
Number of Medicare Beneficiaries                            3161 non-null int64
Number of Distinct Medicare Beneficiary/Per Day Services    3161 non-null int64
Average Medicare Allowed Amount                             3161 non-null float64
Average Submitted Charge Amount                             3161 non-null float64
Average Medicare Payment Amount                             3161 non-null float64
Average Medicare Standardized Amount                        3161 non-null float64
dtypes: float64(5), int64(3), object(18)
memory usage: 642.2+ KB
None

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,HCPCS Code,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount
0,1003011578,RICHARDSON,GAA,O,M.D.,F,I,415 N CENTER ST,SUITE 300,HICKORY,...,43249,Balloon dilation of esophagus using an endoscope,N,26.0,26,26,122.258846,783.000,95.612308,100.033462
1,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,NaN,O,1006 NUT TREE ROAD,NaN,VACAVILLE,...,43249,Balloon dilation of esophagus using an endoscope,N,20.0,16,20,814.534500,2408.400,596.400500,447.812500
2,1003040981,SHAH,AKSHAY,V,M.D.,M,I,14155 N 83RD AVE,SUITE 122,PEORIA,...,43249,Balloon dilation of esophagus using an endoscope,N,25.0,24,25,118.805200,479.000,85.632400,84.749600
3,1003041625,GRAHAM,GEOFFREY,G,D.O.,M,I,2216 E 32ND ST,SUITE 201,JOPLIN,...,43249,Balloon dilation of esophagus using an endoscope,N,16.0,15,16,124.320000,728.125,95.510625,101.753125
4,1003078973,TRIVEDI,CHIRAG,D,D.O.,M,I,13640 N 99TH AVE STE 600,SUITE C-3,SUN CITY,...,43249,Balloon dilation of esophagus using an endoscope,N,17.0,16,17,140.833529,632.000,110.417647,112.217647

In [4]:
hcpcs_pay_43249['zip_fixed'] = hcpcs_pay_43249['Zip Code of the Provider'].str[:5]
hcpcs_pay_43249.head()

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount,zip_fixed
0,1003011578,RICHARDSON,GAA,O,M.D.,F,I,415 N CENTER ST,SUITE 300,HICKORY,...,Balloon dilation of esophagus using an endoscope,N,26.0,26,26,122.258846,783.000,95.612308,100.033462,28601
1,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,NaN,O,1006 NUT TREE ROAD,NaN,VACAVILLE,...,Balloon dilation of esophagus using an endoscope,N,20.0,16,20,814.534500,2408.400,596.400500,447.812500,95687
2,1003040981,SHAH,AKSHAY,V,M.D.,M,I,14155 N 83RD AVE,SUITE 122,PEORIA,...,Balloon dilation of esophagus using an endoscope,N,25.0,24,25,118.805200,479.000,85.632400,84.749600,85381
3,1003041625,GRAHAM,GEOFFREY,G,D.O.,M,I,2216 E 32ND ST,SUITE 201,JOPLIN,...,Balloon dilation of esophagus using an endoscope,N,16.0,15,16,124.320000,728.125,95.510625,101.753125,64804
4,1003078973,TRIVEDI,CHIRAG,D,D.O.,M,I,13640 N 99TH AVE STE 600,SUITE C-3,SUN CITY,...,Balloon dilation of esophagus using an endoscope,N,17.0,16,17,140.833529,632.000,110.417647,112.217647,85351

In [5]:
#for dropping columns

hcpcs_pay_43429 = hcpcs_pay_43249.drop(columns = ['Middle Initial of the Provider', 
                                                  'Credentials of the Provider',
                                                  'Gender of the Provider',
                                                  'Street Address 2 of the Provider',
                                                  'Zip Code of the Provider'])
hcpcs_pay_43429.head()

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,City of the Provider,State Code of the Provider,Country Code of the Provider,Provider Type,Medicare Participation Indicator,...,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount,zip_fixed
0,1003011578,RICHARDSON,GAA,I,415 N CENTER ST,HICKORY,NC,US,Gastroenterology,Y,...,Balloon dilation of esophagus using an endoscope,N,26.0,26,26,122.258846,783.000,95.612308,100.033462,28601
1,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,O,1006 NUT TREE ROAD,VACAVILLE,CA,US,Ambulatory Surgical Center,Y,...,Balloon dilation of esophagus using an endoscope,N,20.0,16,20,814.534500,2408.400,596.400500,447.812500,95687
2,1003040981,SHAH,AKSHAY,I,14155 N 83RD AVE,PEORIA,AZ,US,Gastroenterology,Y,...,Balloon dilation of esophagus using an endoscope,N,25.0,24,25,118.805200,479.000,85.632400,84.749600,85381
3,1003041625,GRAHAM,GEOFFREY,I,2216 E 32ND ST,JOPLIN,MO,US,Gastroenterology,Y,...,Balloon dilation of esophagus using an endoscope,N,16.0,15,16,124.320000,728.125,95.510625,101.753125,64804
4,1003078973,TRIVEDI,CHIRAG,I,13640 N 99TH AVE STE 600,SUN CITY,AZ,US,Gastroenterology,Y,...,Balloon dilation of esophagus using an endoscope,N,17.0,16,17,140.833529,632.000,110.417647,112.217647,85351

In [6]:
hcpcs_entity_code = hcpcs_pay_43249[hcpcs_pay_43249['Entity Type of the Provider'] == 'O']
print(hcpcs_entity_code.shape)
hcpcs_entity_code.head()

(617, 27)

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount,zip_fixed
1,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,NaN,O,1006 NUT TREE ROAD,NaN,VACAVILLE,...,Balloon dilation of esophagus using an endoscope,N,20.0,16,20,814.53450,2408.4,596.400500,447.812500,95687
5,1003079187,WASC LLC,NaN,NaN,NaN,NaN,O,3373 COMMERCE PARKWAY,SUITE 1,WOOSTER,...,Balloon dilation of esophagus using an endoscope,N,17.0,15,17,555.31000,1850.0,433.162941,474.892941,44691
6,1003220187,"CENTRAL OHIO ENDOSCOPY CENTER, LLC",NaN,NaN,NaN,NaN,O,3400 OLENTANGY RIVER RD,NaN,COLUMBUS,...,Balloon dilation of esophagus using an endoscope,N,94.0,79,94,596.51000,750.5,463.132234,478.148830,43202
10,1003815242,"DOTHAN SURGERY CENTER, LLC",NaN,NaN,NaN,NaN,O,1450 ROSS CLARK CIR,SUITE 4,DOTHAN,...,Balloon dilation of esophagus using an endoscope,N,446.0,409,446,509.85778,1300.0,391.675538,477.716614,36301
20,1003887225,CENTRAL TEXAS ENDOSCOPY CENTER LLC,NaN,NaN,NaN,NaN,O,2206 E. VILLA MARIA,NaN,BRYAN,...,Balloon dilation of esophagus using an endoscope,N,26.0,23,26,576.83000,1752.0,445.692692,470.542692,77802

In [7]:
hcpcs_entity_code_asc = hcpcs_entity_code[hcpcs_entity_code['Provider Type'] == 'Ambulatory Surgical Center']
print(hcpcs_entity_code_asc.shape)
hcpcs_entity_code_asc.head()

(616, 27)

,National Provider Identifier,Last Name/Organization Name of the Provider,First Name of the Provider,Middle Initial of the Provider,Credentials of the Provider,Gender of the Provider,Entity Type of the Provider,Street Address 1 of the Provider,Street Address 2 of the Provider,City of the Provider,...,HCPCS Description,HCPCS Drug Indicator,Number of Services,Number of Medicare Beneficiaries,Number of Distinct Medicare Beneficiary/Per Day Services,Average Medicare Allowed Amount,Average Submitted Charge Amount,Average Medicare Payment Amount,Average Medicare Standardized Amount,zip_fixed
1,1003015843,"NORTHBAY PHYSICIAN'S SURGERY CENTER, L.L.C.",NaN,NaN,NaN,NaN,O,1006 NUT TREE ROAD,NaN,VACAVILLE,...,Balloon dilation of esophagus using an endoscope,N,20.0,16,20,814.53450,2408.4,596.400500,447.812500,95687
5,1003079187,WASC LLC,NaN,NaN,NaN,NaN,O,3373 COMMERCE PARKWAY,SUITE 1,WOOSTER,...,Balloon dilation of esophagus using an endoscope,N,17.0,15,17,555.31000,1850.0,433.162941,474.892941,44691
6,1003220187,"CENTRAL OHIO ENDOSCOPY CENTER, LLC",NaN,NaN,NaN,NaN,O,3400 OLENTANGY RIVER RD,NaN,COLUMBUS,...,Balloon dilation of esophagus using an endoscope,N,94.0,79,94,596.51000,750.5,463.132234,478.148830,43202
10,1003815242,"DOTHAN SURGERY CENTER, LLC",NaN,NaN,NaN,NaN,O,1450 ROSS CLARK CIR,SUITE 4,DOTHAN,...,Balloon dilation of esophagus using an endoscope,N,446.0,409,446,509.85778,1300.0,391.675538,477.716614,36301
20,1003887225,CENTRAL TEXAS ENDOSCOPY CENTER LLC,NaN,NaN,NaN,NaN,O,2206 E. VILLA MARIA,NaN,BRYAN,...,Balloon dilation of esophagus using an endoscope,N,26.0,23,26,576.83000,1752.0,445.692692,470.542692,77802

In [8]:
zip_crosswalk_df = pd.read_excel('../data/CBSA_ZIP_032020.xlsx', dtype = {'ZIP': str})
zip_crosswalk_df.sample(10)

        CBSA    ZIP  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
12002  24330  55769   0.053082   0.056156   0.022388   0.052611
2347   12580  21797   0.002747   0.000951   0.000768   0.002500
18348  31300  28378   0.000000   0.000000   0.001203   0.000016
39860  99999  59547   0.000002   0.000000   0.000004   0.000002
31800  44420  24439   0.001636   0.000385   0.000000   0.001489
3108   13700  79733   0.000067   0.000711   0.000000   0.000120
27705  40340  55964   0.019112   0.024766   0.012561   0.019216
45803  99999  15861   0.000009   0.000005   0.000013   0.000009
42163  99999  42064   0.000441   0.000477   0.000412   0.000442
34450  47900  20195   0.000477   0.001718   0.000013   0.000550

In [17]:
hospcharge_apc = pd.read_csv('../data/Provider_Outpatient_Hospital_Charge_Data_by_APC__CY2017.csv', 
                             dtype = {'Provider_Zip_Code': str})
hospcharge_apc.head()

,Provider_ID,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,Provider_HRR,APC,APC_Desc,Beneficiaries,CAPC_Services,Average_Total_Submitted_Charges,Average_Medicare_Allowed_Amount,Average_Medicare_Payment_Amount,Outlier_Services,Average_Medicare_Outlier_Amount
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249.0,259,9575.01,1038.45,826.28,NaN,NaN
1,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52.0,53,12578.28,1792.60,1423.25,NaN,NaN
2,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26.0,27,11337.61,2113.58,1683.99,0.0,0.0
3,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23.0,23,17116.16,3737.14,2977.55,0.0,0.0
4,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17.0,17,7382.73,1029.46,820.21,0.0,0.0

In [22]:
hospcharge_apc['zip_fixed'] = hospcharge_apc['Provider_Zip_Code'].str[:5]
hospcharge_apc.head(10)

,Provider_ID,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,Provider_HRR,APC,APC_Desc,Beneficiaries,CAPC_Services,Average_Total_Submitted_Charges,Average_Medicare_Allowed_Amount,Average_Medicare_Payment_Amount,Outlier_Services,Average_Medicare_Outlier_Amount,zip_fixed
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249.0,259,9575.01,1038.45,826.28,NaN,NaN,36301
1,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52.0,53,12578.28,1792.60,1423.25,NaN,NaN,36301
2,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26.0,27,11337.61,2113.58,1683.99,0.0,0.0,36301
3,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23.0,23,17116.16,3737.14,2977.55,0.0,0.0,36301
4,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17.0,17,7382.73,1029.46,820.21,0.0,0.0,36301
5,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5113,Level 3 Musculoskeletal Procedures,65.0,68,12500.44,1970.91,1570.32,0.0,0.0,36301
6,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5114,Level 4 Musculoskeletal Procedures,173.0,175,20738.62,4399.54,3502.09,0.0,0.0,36301
7,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5115,Level 5 Musculoskeletal Procedures,59.0,59,32460.51,8078.53,6762.53,0.0,0.0,36301
8,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5153,Level 3 Airway Endoscopy,20.0,20,8477.08,1073.75,855.51,0.0,0.0,36301
9,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5154,Level 4 Airway Endoscopy,28.0,28,9904.53,1974.13,1556.27,0.0,0.0,36301

In [23]:
hosphcpcs_asc_only = hospcharge_apc[hospcharge_apc(['Provider_State'] == 'TN']
print(hcpcs_asc_only.shape)
hcpcs_asc_only.head()

SyntaxError: invalid syntax (<ipython-input-23-f6419a58ff2d>, line 1)

In [ ]:
hcpcs_43249_asc_tn = hcpcs_entity_code[hcpcs_entity_code['Provider Type'] == 'Ambulatory Surgical Center']
print(hcpcs_entity_code_asc.shape)
hcpcs_entity_code_asc.head()

In [24]:
apc_hospital_5302 = pd.read_csv('../data/apc_hospital_5302.csv')
print(apc_hospital_5302.shape)
apc_hospital_5302.head()

(2261, 16)

,Provider_ID,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,Provider_HRR,APC,APC_Desc,Beneficiaries,CAPC_Services,Average_Total_Submitted_Charges,Average_Medicare_Allowed_Amount,Average_Medicare_Payment_Amount,Outlier_Services,Average_Medicare_Outlier_Amount
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5302,Level 2 Upper GI Procedures,165.0,177,10380.96,1123.67,894.25,0.0,0.0
1,10005,Marshall Medical Center South,2505 U S Highway 431 North,Boaz,AL,35957,AL - Birmingham,5302,Level 2 Upper GI Procedures,48.0,64,3875.07,1148.72,912.36,0.0,0.0
2,10006,Eliza Coffee Memorial Hospital,205 Marengo Street,Florence,AL,35631,AL - Birmingham,5302,Level 2 Upper GI Procedures,193.0,229,5355.04,1048.26,831.00,0.0,0.0
3,10011,St Vincent's East,50 Medical Park East Drive,Birmingham,AL,35235,AL - Birmingham,5302,Level 2 Upper GI Procedures,88.0,89,6510.94,1105.35,868.94,0.0,0.0
4,10012,Dekalb Regional Medical Center,200 Med Center Drive,Fort Payne,AL,35968,AL - Birmingham,5302,Level 2 Upper GI Procedures,78.0,81,9088.11,1143.93,904.27,0.0,0.0